//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка не может быть пустой!.
        /// </summary>
        internal static string CantBeNull {
            get {
                return ResourceManager.GetString("CantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить язык.
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правильное слово! Ход переходит следующему игроку..
        /// </summary>
        internal static string CorrectWord {
            get {
                return ResourceManager.GetString("CorrectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый игрок.
        /// </summary>
        internal static string FirstPlayer {
            get {
                return ResourceManager.GetString("FirstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный размер строки!.
        /// </summary>
        internal static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение!.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В вашем слове больше букв {letterOfWord}, чем в первоначальном! Попробуйте другое слово..
        /// </summary>
        internal static string MoreThen {
            get {
                return ResourceManager.GetString("MoreThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никнейм не может быть пустым!.
        /// </summary>
        internal static string NameCantBeNull {
            get {
                return ResourceManager.GetString("NameCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В первоначальном слове нет буквы {letterOfWord}! Попробуйте другое слово..
        /// </summary>
        internal static string NoLetter {
            get {
                return ResourceManager.GetString("NoLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В слове не могут быть не-алфавитные символы!.
        /// </summary>
        internal static string NonAlphabet {
            get {
                return ResourceManager.GetString("NonAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый игрок, введите свой никнейм: .
        /// </summary>
        internal static string Player1Input {
            get {
                return ResourceManager.GetString("Player1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второй игрок, введите свой никнейм: .
        /// </summary>
        internal static string Player2Input {
            get {
                return ResourceManager.GetString("Player2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите любую клавишу для продолжения..
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начале игры, нужно ввести начальное слово..
        /// </summary>
        internal static string RuleString1 {
            get {
                return ResourceManager.GetString("RuleString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только из букв начального слова игрокам нужно по очереди вводить слова..
        /// </summary>
        internal static string RuleString2 {
            get {
                return ResourceManager.GetString("RuleString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На ввод правильного слова дается 20 секунд иначе вы проиграли..
        /// </summary>
        internal static string RuleString3 {
            get {
                return ResourceManager.GetString("RuleString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второй игрок.
        /// </summary>
        internal static string SecondPlayer {
            get {
                return ResourceManager.GetString("SecondPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать игру.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное слово.
        /// </summary>
        internal static string StartWord {
            get {
                return ResourceManager.GetString("StartWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время вышло! {nameOfCurrentPlayer} проиграл!.
        /// </summary>
        internal static string TimesUp {
            get {
                return ResourceManager.GetString("TimesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это слово уже было! Введите другое..
        /// </summary>
        internal static string TryAnother {
            get {
                return ResourceManager.GetString("TryAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Победитель: {nameOfCurrentPlayer}!.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите слово от 8 до 30 символов.
        /// </summary>
        internal static string WriteF8T30 {
            get {
                return ResourceManager.GetString("WriteF8T30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {nameOfCurrentPlayer}, введите слово: .
        /// </summary>
        internal static string WriteWord {
            get {
                return ResourceManager.GetString("WriteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш выбор.
        /// </summary>
        internal static string YourChoice {
            get {
                return ResourceManager.GetString("YourChoice", resourceCulture);
            }
        }
    }
}
